version: '3.4'

services:
  mssqlaccessor:
    image: kpiatigorskii/mssqlaccessor
    build:
      context: .
      dockerfile: CompetitionBack/Dockerfile
    ports:
     - 7277:80

  competitionfront:
    image: kpiatigorskii/competitionfront
    build:
      context: .
      dockerfile: CompetitionFront/Dockerfile
    ports:
     - 7130:80

#networks:
#  default:
#    external:
#      name: bridge